stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - .env
    - src/data_ingestion.py
    outs:
    - data/raw/reviews.csv
  preprocess_data_SVD:
    cmd: python src/SVD/preprocess.py
    deps:
    - data/raw/reviews.csv
    - src/SVD/preprocess.py
    outs:
    - data/processed/SVD/ratings.csv
  train_SVD:
    cmd: python src/SVD/train.py
    deps:
    - config/params.yaml
    - data/processed/SVD/ratings.csv
    - src/SVD/train.py
    outs:
    - models/svd_model.pkl
  tune_SVD:
    cmd: python src/SVD/tune.py
    deps:
    - data/processed/SVD/ratings.csv
    - src/SVD/tune.py
    outs:
    - config/params.yaml
