stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - .env
    - src/data_ingestion.py
    - config/ingestion.yaml
    outs:
    - data/raw/reviews.csv
    - data/raw/games.csv
  preprocess_SVD:
    cmd: python src/SVD/preprocess.py
    deps:
    - data/raw/reviews.csv
    - src/SVD/preprocess.py
    - config/SVD/preprocess.yaml
    outs:
    - data/processed/SVD/train.csv
    - data/processed/SVD/test.csv
  train_SVD:
    cmd: python src/SVD/train.py
    deps:
    - config/SVD/params.yaml
    - data/processed/SVD/train.csv
    - data/processed/SVD/test.csv
    - src/SVD/train.py
    - config/SVD/train.yaml
    outs:
    - models/svd_model.pkl
  tune_SVD:
    cmd: python src/SVD/tune.py
    deps:
    - data/processed/SVD/train.csv
    - src/SVD/tune.py
    - config/SVD/tune.yaml
    outs:
    - config/SVD/params.yaml
