{
 "title": "SE4AI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CTR (Click-Through Rate) ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(recommendation_clicks_total[5m]) / rate(recommendations_total[5m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Score Previsioni",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predicted_score_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentuale di Fallback",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fallback_users_total[5m]) / rate(prediction_request_total[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Totale Richieste Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tempo di Risposta Medio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])\r\n/\r\nrate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}