global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']


# QUESTO FILE È DA USARE AVVIANDO IN LOCALE IL PROGETTO
# ED AVVIANDO PPROMETHEUS TRAMITE DOCKER
