name: CI Pipeline

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff dvc

      - name: Run linter (ruff)
        run: |
          ruff check src/* --output-format=github

      - name: Check Python compile
        run: |
          find src/ -name "*.py" | xargs -n 1 python -m py_compile

      - name: Check DVC pipeline status
        run: |
          dvc status
